//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.DiemDanhSV
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DM_MON_HOC
    {
        [Display(Name = "ID")]
        public int id { get; set; }

        [Required(ErrorMessage = "Tên môn học là trường bắt buộc")]
        [StringLength(100, MinimumLength = 3)]
        [Display(Name = "Tên môn học")]
        public string TenMonHoc { get; set; }

        [Required(ErrorMessage = "Số tín chỉ là trường bắt buộc")]
        [Range(1, 20, ErrorMessage ="Số tín chỉ không đúng!")]
        [Display(Name = "Số tín chỉ")]
        public Nullable<int> SoTinChi { get; set; }
    }
}
