//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.DiemDanhSV
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class LOP_MON
    {
        [Display(Name = "ID")]
        public int id { get; set; }

        [Required(ErrorMessage = "ID lớp là trường bắt buộc")]
        [Display(Name = "ID lớp")]
        public Nullable<int> IdLop { get; set; }

        [Required(ErrorMessage = "ID môn học là trường bắt buộc")]
        [Display(Name = "ID môn học")]
        public Nullable<int> IdMonHoc { get; set; }

        [Required(ErrorMessage = "ID giảng viên là trường bắt buộc")]
        [Display(Name = "ID giảng viên")]
        public Nullable<int> IdGiangVien { get; set; }

        [Display(Name = "Phòng học")]
        public string PhongHoc { get; set; }

        [Display(Name = "Ngày tạo")]
        public Nullable<System.DateTime> NgayTao { get; set; }

        [Display(Name = "Người tạo")]
        public Nullable<int> NguoiTao { get; set; }

        [Display(Name = "Ngày sửa")]
        public Nullable<System.DateTime> NgaySua { get; set; }

        [Display(Name = "Người sửa")]
        public Nullable<int> NguoiSua { get; set; }
    }
}
