//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.DiemDanhSV
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DiemDanhSvDbEntities : DbContext
    {
        public DiemDanhSvDbEntities()
            : base("name=DiemDanhSvDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DIEM_DANH> DIEM_DANH { get; set; }
        public virtual DbSet<DM_MON_HOC> DM_MON_HOC { get; set; }
        public virtual DbSet<GIANG_VIEN> GIANG_VIEN { get; set; }
        public virtual DbSet<LOP> LOPs { get; set; }
        public virtual DbSet<LOP_MON> LOP_MON { get; set; }
        public virtual DbSet<QL_PHONG_DT> QL_PHONG_DT { get; set; }
        public virtual DbSet<QUYEN> QUYENs { get; set; }
        public virtual DbSet<QUYEN_CHUCNANG> QUYEN_CHUCNANG { get; set; }
        public virtual DbSet<SINH_VIEN> SINH_VIEN { get; set; }
        public virtual DbSet<TAI_KHOAN> TAI_KHOAN { get; set; }
        public virtual DbSet<SINH_VIEN_LOP_MON> SINH_VIEN_LOP_MON { get; set; }
    }
}
