//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.DiemDanhSV
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUYEN_CHUCNANG
    {
        public int Id { get; set; }
        public Nullable<int> IdQuyen { get; set; }
        public string ChucNang { get; set; }
        public string Url { get; set; }
        public string Controller { get; set; }
        public string PhuongThuc { get; set; }
    }
}
