//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.DiemDanhSV
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TAI_KHOAN
    {
        [Display(Name = "ID")]
        public int id { get; set; }

        [Required(ErrorMessage ="Tên đăng nhập là trường bắt buộc")]
        [StringLength(100, MinimumLength =3)]
        [Display(Name = "Tên đăng nhập")]
        public string TenDangNhap { get; set; }

        [Required(ErrorMessage = "Mật khẩu là trường bắt buộc")]
        [StringLength(100, MinimumLength = 8)]
        [Display(Name = "Mật khẩu")]
        public string MatKhau { get; set; }

        [Required(ErrorMessage = "Tên hiển thị là trường bắt buộc")]
        [StringLength(100, MinimumLength = 3)]
        [Display(Name = "Tên hiển thị")]
        public string TenHienThi { get; set; }

        [Required(ErrorMessage = "Quyền là trường bắt buộc")]
        [Range(1, 5, ErrorMessage ="Giá trị quyền không đúng!")]
        [Display(Name = "Id quyền")]
        public Nullable<int> IdQuyen { get; set; }

        [Display(Name = "Là cán bộ phòng đào tạo")]
        public Nullable<bool> IsQlPhongDT { get; set; }

        [Display(Name = "Là giảng viên")]
        public Nullable<bool> IsGiangVien { get; set; }

        [Display(Name = "Là sinh viên")]
        public Nullable<bool> IsSinhVien { get; set; }

        [Display(Name = "Id cán bộ phòng đào tạo")]
        public Nullable<int> IdQlPhongDT { get; set; }

        [Display(Name = "Id giảng viên")]
        public Nullable<int> IdGiangVien { get; set; }

        [Display(Name = "Id sinh viên")]
        public Nullable<int> IdSinhVien { get; set; }

        [Display(Name = "Ngày tạo")]
        public Nullable<System.DateTime> NgayTao { get; set; }

        [Display(Name = "Người tạo")]
        public Nullable<int> NguoiTao { get; set; }

        [Display(Name = "Ngày sửa")]
        public Nullable<System.DateTime> NgaySua { get; set; }

        [Display(Name = "Người sửa")]
        public Nullable<int> NguoiSua { get; set; }
    }
}
